### ISSUE TITLE
Add if __name__ == '__main__':

### ISSUE THREAD

**Issue by yoelk** [ubershmekel/abs_ratio#1]
Hi,
I've downloaded your abs_ratio and decided to put it into my project ([Instrumentino](https://github.com/yoelk/Instrumentino2)).

I got an error because your test code.
You can avoid it by adding this line before your test code:
`if __name__ == '__main__':`

Cheers,
Joel

**Comment by ubershmekel** [comment]
Fixed in 360f4a43e75d2fb8f96e62e472be154c91c53ab1

Thanks for opening the issue.
